FROM python:3.13-slim-bookworm

WORKDIR /Cars24_app_docker

RUN python3 -m pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]

