FROM python:3.13-slim-buster
WORKDIR /Cars24_app_docker

RUN python3 -m pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
CMD [ "python", "-m", "flask", "--host==0.0.0.0" ]